### ISSUE TITLE
Finding flaky tests on 2018-q1-master

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/google-cloud-visualstudio#906]
The build has been failing on and off for a few days now. We probably have some flaky tests. The tests don't fail apparently, the build just hangs. Investigating.

**Comment by amanda-tarafa** [comment]
After a couple of days of testing on my fork here are my conclusions:

Testing is flaky because we effectively have some `async void` tests, which means that we effectively have some asynchronous tests. These sometimes make vstest crash.

Tests reference in #898 are some of those effectively `async void` tests. Even though they are not defined as `async void`, they are testing 
`LogsViewerViewModel.SubmitAdvanceFilterCommand.Execute`
and
`LogsViewerViewModel.SimpleTextSearchCommand.Execute`
which in turn are calling
`ErrorHandlerUtils.HandleAsyncExceptions(ReloadAsync)`
which is defined as
`public static async void HandleAsyncExceptions(Func<Task> task)`
i.e., `async void`.
This effectively makes the calls to `LogsViewerViewModel.SubmitAdvanceFilterCommand.Execute` and `LogsViewerViewModel.SimpleTextSearchCommand.Execute`. And probably the fact that these two tests need two identical calls to `Execute` is just prove that these calls are asynchronous, the second call to `Execute` is only improving the chances of the first one having finished thus allowing the `Asserts` to pass. We probably have several other tests like these, given that several Commands are calling `ErrorHandlerUtils.HandleAsyncExceptions(ReloadAsync)`, and maybe other `async void` methods.

`async void` tests [are not considered good tests](https://msdn.microsoft.com/en-us/magazine/dn818493.aspx) since they are effectively fire and forget (we don't have a Task to keep track of the execution). And as far as I can tell by going through [vstest docs](https://github.com/Microsoft/vstest-docs) and [vstest code](https://github.com/Microsoft/vstest), it does not support `async void` test.

What I've done:
In #907 I've added code to print the vstest diagnostics file whenever vstest crashes. This will hopefully allow us to see why it crashes exactly every time. Curiously, just by generating the diagnostics file, flakiness has stopped, just because by making vstest write diagnostics info we are probably giving task enough time to finish without tests conflicting with one another.

Solutions:
First we need to identify all of our `async void` tests.
And then remove them.
Or some of our `async void` methods can be changed for `asyn Task` (vstest supports `async Task` tests, it can wait for the Task to be done before moving on to the next test). Our Commands though are not easily changeable to `async Task`, we would probably need to implement a `ProtectedCommandAsync`, and this might be a big undertaking.

@iantalarico , @ILMTitan happy to hear your thoughts about this.

**Comment by iantalarico** [comment]
@amanda-tarafa 100% agree here would should not have any async void tests.  We should fix them or remove them.

**Comment by amanda-tarafa** [comment]
OK, I'll start working on this. Will fix as many as I can and remove the rest. This is going to take some time though.
Also, now the #907 failed, I'm looking at the diagnostics info to see if it helps figuring out what happened.

**Comment by amanda-tarafa** [comment]
Update: No relevant info on the diagnostics file. The writing on the file just stops when vstest crashes. Nothing abnormal written on the file at any point before the crash as far as I can see.
Will be adding the additional diagnostic files as artifacts on appveyor: log.host.*.txt. Will run some tests in my fork before moving on to the public repo.

**Comment by amanda-tarafa** [comment]
[Doc](https://docs.google.com/document/d/1-3FzWUiikFzwV2vHcXlF3s21h6AZFQjHG_BpAnxIDlo) explaining what the problem was.
Quick fix on #918.
Issues for permanent fixes: #914, #915, #916, #917.

**Comment by amanda-tarafa** [comment]
Quick reference comment, we still don't have log.host.*.txt files because we are using VS 2015. See [this one](https://github.com/Microsoft/vstest/issues/1485).
